# frozen_string_literal: true
source "https://rubygems.org"
gem 'pry'
gem "rspec"
gem "sinatra-activerecord"
gem "sqlite3"
gem "rake"
gem 'json'
gem "database_cleaner"
gem "require_all"
gem "colorize"
gem "launchy"
gem 'tty-prompt'
gem 'tty-font'
gem 'pastel'
gem 'pry-rescue'
gem "table_print"
gem 'terminal-table'
gem 'tty-screen'
gem 'tty-progressbar'
gem 'tty-box'
